In [1]:
str="priya"
print("the string is : ",str)

the string is :  priya


In [2]:
str[1]='a'
str

TypeError: 'str' object does not support item assignment

In [3]:
list1=[4,7,2,9]
print("The list is : ",list1)
list1[2]=5
print("After change the content of index 2 : ",list1)

The list is :  [4, 7, 2, 9]
After change the content of index 2 :  [4, 7, 5, 9]


In [4]:
list2=[4,7,2,9]
print("The list is : ",list2)
print("the contnt of index 2 : ",list2[2])
print("the element in -1 : ",list2[-1])

The list is :  [4, 7, 2, 9]
the contnt of index 2 :  2
the element in -1 :  9


In [5]:
zlist=[0]*10
print("the element of zlist is :",zlist)

the element of zlist is : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [42]:
list3=[3,9,2,7,8,7,7]
print("the initial list is :",list3)
n=min(list3)
print("Min of the list elements is :",n)

the initial list is : [3, 9, 2, 7, 8, 7, 7]
Min of the list elements is : 2


In [10]:
list1=[3,7,4,0,2]
for i in list1:
    print(i)

3
7
4
0
2


In [39]:
list1=[1,2,3,4,5]
print("Initial list is :",list1)
for i in range(len(list1)):
    list1[i]=list1[i]+1
print("Now the list is :",list1)

Initial list is : [1, 2, 3, 4, 5]
Now the list is : [2, 3, 4, 5, 6]


In [15]:
list1=[1,2,3,4,5]
list1[1:3]

[2, 3]

In [18]:
str1="i am priya"
str2=str1.split()
print(str2)

['i', 'am', 'priya']


In [19]:
list1=[7,4,0,2,1]
n=len(list1)
print("The length of list1 :",n)

The length of list1 : 5


In [22]:
List = [1,2,5,9,4,8,7,2]
print("Intial List: ",List)
SList = List[1:3]
print("Slicing elements in a range 1-3: ",SList)
SList = List[2:]
print("Elements sliced from 2th element till the end: ",SList)
SList = List[:]
print("Printing all elements using slice operation: ",SList)

Intial List:  [1, 2, 5, 9, 4, 8, 7, 2]
Slicing elements in a range 1-3:  [2, 5]
Elements sliced from 2th element till the end:  [5, 9, 4, 8, 7, 2]
Printing all elements using slice operation:  [1, 2, 5, 9, 4, 8, 7, 2]


In [43]:
eDictionary = {}
print ("The emptyDictionary is:", eDictionary )

The emptyDictionary is: {}


In [44]:
grades = { "a": 87, "b": 76, "c": 92, "d": 89 }
print ("All grades:", grades )

All grades: {'a': 87, 'b': 76, 'c': 92, 'd': 89}


In [45]:
grades = { "a": 87, "b": 76, "c": 92, "d": 89 }
print ("a's current grade:", grades[ "a" ] )
grades[ "a" ] = 90
print ("a's new grade:", grades[ "a" ] )

a's current grade: 87
a's new grade: 90


In [50]:
grades = { "a": 87, "b": 76, "c": 92, "d": 89 }
print ("Initial all grades:", grades )
grades[ "e" ] = 93
print ("Dictionary grades after modification:",grades )

Initial all grades: {'a': 87, 'b': 76, 'c': 92, 'd': 89}
Dictionary grades after modification: {'a': 87, 'b': 76, 'c': 92, 'd': 89, 'e': 93}


In [49]:
grades = { "a": 87, "b": 76, "c": 92, "d": 89 }
print ("Initial all grades:", grades )
del grades[ "d" ]
print ("Dictionary grades after deletion:",grades )

Initial all grades: {'a': 87, 'b': 76, 'c': 92, 'd': 89}
Dictionary grades after deletion: {'a': 87, 'b': 76, 'c': 92}


In [53]:
grades = { "a": 87, "b": 76, "c": 92, "d": 89 }
for key in grades:
    print(key)
for key,value in grades.items():
    print(key, '-->', value)

a
b
c
d
a --> 87
b --> 76
c --> 92
d --> 89


In [2]:
grades = { "a": 87, "b": 76, "c": 92, "d": 89 }
key=grades.keys()
print(key)

dict_keys(['a', 'b', 'c', 'd'])


In [56]:
import numpy as np
sa=np.array([1,2,3])
print(sa)

[1 2 3]


In [60]:
import numpy as np
mA = np.array([[1, 2, 3], [3, 4, 5]])
print(mA)
mA = np.array([[1.1, 2, 3], [3, 4, 5]])
print(mA)
mA = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex)
print(mA)

[[1 2 3]
 [3 4 5]]
[[1.1 2.  3. ]
 [3.  4.  5. ]]
[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


In [4]:
import numpy as np
a = np.array([[1, 2, 3], [3, 4, 5],[4,5,6]])
print("Array is :\n",a)
print("dimension is :",a.ndim)
print("Shape :",a.shape)
print("data type is :",a.dtype)

Array is :
 [[1 2 3]
 [3 4 5]
 [4 5 6]]
dimension is : 2
Shape : (3, 3)
data type is : int32


In [68]:
import numpy as np
A1 = np.array([[2, 4], [5, -6]])
print("First Array is :\n",A1)
A2 = np.array([[9, -3], [3, 6]])
print("Second Array is :\n",A2)
RA = A1.dot(A2)
print("After multiply two array :\n",RA)

First Array is :
 [[ 2  4]
 [ 5 -6]]
Second Array is :
 [[ 9 -3]
 [ 3  6]]
After multiply two array :
 [[ 30  18]
 [ 27 -51]]


In [11]:
import numpy as np
a=np.ones(5)
print(a)
print()
b=np.ones((2,3))
print(b)
print()
c=np.ones((3,4),dtype=int)
print(c)
print()

[1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]



In [16]:
import numpy as np
a=np.arange(3,7)
print(a)
b=np.arange(2,9,2,float)
print(b)

[3 4 5 6]
[2. 4. 6. 8.]


In [19]:
import numpy as np
a=np.ones((2,4))
print("First array is:\n",a)
b=np.zeros((3,4))
print("Second array is:\n",b)
c=np.concatenate([a,b])
print("Concatenated array is:\n",c)

First array is:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Second array is:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Concatenated array is:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
import numpy as np
a=np.array([[1,2,4],[5,6,7]])
print("First array is:\n",a)
print("\ndata type is",a.dtype)
b=a.astype(complex)
print("\nAfter changing datatype ,the array is:\n",b)

First array is:
 [[1 2 4]
 [5 6 7]]

data type is int32

After changing datatype ,the array is:
 [[1.+0.j 2.+0.j 4.+0.j]
 [5.+0.j 6.+0.j 7.+0.j]]


In [38]:
import numpy as np
a=np.random.rand(10)
print("The array is:\n",a)

The array is:
 [0.58937292 0.38379229 0.50001865 0.73802438 0.112956   0.50733631
 0.20506082 0.67445669 0.564774   0.99065735]


In [37]:
import numpy as np
a=np.linspace(2,3,num=5,retstep=True,dtype=float,endpoint=True)
print("The array is:\n",a)

The array is:
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


In [30]:
import pandas as pd
result={'Name':['priya','hridoy','tanvir','susmita'],
        'Math':[90,91,92,91],
        'stat':[80,81,82,81],
        'DM':[90,91,92,93]}
df=pd.DataFrame(result)
print("The Result table is:\n",df)
print("\nMinimum values are:\n",df.min())

The Result table is:
       Name  Math  stat  DM
0    priya    90    80  90
1   hridoy    91    81  91
2   tanvir    92    82  92
3  susmita    91    81  93

Minimum values are:
 Name    hridoy
Math        90
stat        80
DM          90
dtype: object


In [35]:
import pandas as pd
result={'Name':['priya','hridoy','tanvir','susmita'],
        'roll':[1,2,3,4],
        'Math':[90,91,92,91],
        'stat':[80,81,82,81],
        'DM':[90,91,92,93]}
df=pd.DataFrame(result)
print("The Result table is:")
print(df)
df2=df[df.Name=='susmita']
print("\nThe Result table for susmita:")
print(df2)
print("\nMinimum marks obtain by susmita:")
print(df2.min(numeric_only=True))

The Result table is:
      Name  roll  Math  stat  DM
0    priya     1    90    80  90
1   hridoy     2    91    81  91
2   tanvir     3    92    82  92
3  susmita     4    91    81  93

The Result table for susmita:
      Name  roll  Math  stat  DM
3  susmita     4    91    81  93

Minimum marks obtain by susmita:
roll     4
Math    91
stat    81
DM      93
dtype: int64


In [27]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
print("The Result table is:")
print(df)
print("\nMaximum marks of each student is:")
print(df.max(numeric_only=True,axis=1))

The Result table is:
      Name  roll  Math  stat  DM
0    priya     1    90    80  90
1   hridoy     2    91    81  91
2   tanvir     3    92    82  92
3  susmita     4    91    81  93

Maximum marks of each student is:
0    90
1    91
2    92
3    93
dtype: int64


In [36]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
print("The Result table is:")
print(df)

The Result table is:
      Name  ut  Math  stat  DM
0    priya   1    90    80  90
1    priya   2    91    81  91
2   hridoy   1    92    82  92
3   hridoy   2    91    81  93
4   tanvir   1    94    83  91
5   tanvir   2    92    82  92
6  susmita   1    90    81  93
7  susmita   2    91    80  91


In [1]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
print("The Result table is:")
print(df)

print("\nMaximum values are:\n",df[df['ut']==2].max(numeric_only=True))

The Result table is:
      Name  ut  Math  stat  DM
0    priya   1    90    80  90
1    priya   2    91    81  91
2   hridoy   1    92    82  92
3   hridoy   2    91    81  93
4   tanvir   1    94    83  91
5   tanvir   2    92    82  92
6  susmita   1    90    81  93
7  susmita   2    91    80  91

Maximum values are:
 ut       2
Math    92
stat    82
DM      93
dtype: int64


In [41]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
print("The Result table is:")
print(df)
print("\nMaximum values are:\n",df.max(numeric_only=True,axis=1))

The Result table is:
      Name  ut  Math  stat  DM
0    priya   1    90    80  90
1    priya   2    91    81  91
2   hridoy   1    92    82  92
3   hridoy   2    91    81  93
4   tanvir   1    94    83  91
5   tanvir   2    92    82  92
6  susmita   1    90    81  93
7  susmita   2    91    80  91

Maximum values are:
 0    90
1    91
2    92
3    93
4    94
5    92
6    93
7    91
dtype: int64


In [50]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'Stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
df2=df.loc[df.Name=='susmita']
print("\nThe Result of Susmita:")
print(df2)
print('\nMinimum values are:\n',df2[['Math','Stat','DM']].min(numeric_only=True))


The Result of Susmita:
      Name  ut  Math  Stat  DM
6  susmita   1    90    81  93
7  susmita   2    91    80  91

Minimum values are:
 Math    90
Stat    80
DM      91
dtype: int64


In [51]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'Stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
df2=df.loc[df.Name=='susmita']
print("\nThe Result of Susmita:")
print(df2)
print('\nTotal marks in each subject is:\n',df2[['Math','Stat','DM']].sum())


The Result of Susmita:
      Name  ut  Math  Stat  DM
6  susmita   1    90    81  93
7  susmita   2    91    80  91

Total marks in each subject is:
 Math    181
Stat    161
DM      184
dtype: int64


In [52]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'Stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
print("The Result table is:")
print(df)
print('\nNumber of values in each row is:\n',df.count(axis=1))

The Result table is:
      Name  ut  Math  Stat  DM
0    priya   1    90    80  90
1    priya   2    91    81  91
2   hridoy   1    92    82  92
3   hridoy   2    91    81  93
4   tanvir   1    94    83  91
5   tanvir   2    92    82  92
6  susmita   1    90    81  93
7  susmita   2    91    80  91

Number of values in each row is:
 0    5
1    5
2    5
3    5
4    5
5    5
6    5
7    5
dtype: int64


In [55]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'Stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
df1=df['Math']
df2=df1[df.ut==1]
print("\nThe Result of math in ut 1:")
print(df2)
print('\nMedian of math in ut 1:\n',df2.median())


The Result of math in ut 1:
0    90
2    92
4    94
6    90
Name: Math, dtype: int64

Median of math in ut 1:
 91.0


In [56]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'Stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
df1=df['Math']
print("\nThe Result of math:")
print(df1)
print('\nMode value of math:\n',df1.mode())


The Result of math:
0    90
1    91
2    92
3    91
4    94
5    92
6    90
7    91
Name: Math, dtype: int64

Mode value of math:
 0    91
Name: Math, dtype: int64


In [61]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'Stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
df1=df['Math']
print("\nThe Result of math:")
print(df1)
print('\n1st quartile value:',df1.quantile(q=.25))
print('2nd quartile value or median:',df1.quantile())
print('3rd quartile value:',df1.quantile(q=.75))


The Result of math:
0    90
1    91
2    92
3    91
4    94
5    92
6    90
7    91
Name: Math, dtype: int64

1st quartile value: 90.75
2nd quartile value or median: 91.0
3rd quartile value: 92.0


In [66]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'Stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
df1=df[['Math','Stat','DM']]
print("\nThe Result of all subject:")
print(df1)
print('\n1st quartile value:')
print(df1.quantile([.25,.75]))


The Result of all subject:
   Math  Stat  DM
0    90    80  90
1    91    81  91
2    92    82  92
3    91    81  93
4    94    83  91
5    92    82  92
6    90    81  93
7    91    80  91

1st quartile value:
       Math   Stat     DM
0.25  90.75  80.75  91.00
0.75  92.00  82.00  92.25


In [68]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'Stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
df1=df['Math']
print("\nThe Result of math:")
print(df1)
print('\nstandard deviation:',df1.std())


The Result of math:
0    90
1    91
2    92
3    91
4    94
5    92
6    90
7    91
Name: Math, dtype: int64

standard deviation: 1.3024701806293193


In [73]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'Stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
print("\nThe Result table:\n",df)
print('\nstatistical values:\n',df.describe())


The Result table:
       Name  ut  Math  Stat  DM
0    priya   1    90    80  90
1    priya   2    91    81  91
2   hridoy   1    92    82  92
3   hridoy   2    91    81  93
4   tanvir   1    94    83  91
5   tanvir   2    92    82  92
6  susmita   1    90    81  93
7  susmita   2    91    80  91

statistical values:
              ut      Math       Stat        DM
count  8.000000   8.00000   8.000000   8.00000
mean   1.500000  91.37500  81.250000  91.62500
std    0.534522   1.30247   1.035098   1.06066
min    1.000000  90.00000  80.000000  90.00000
25%    1.000000  90.75000  80.750000  91.00000
50%    1.500000  91.00000  81.000000  91.50000
75%    2.000000  92.00000  82.000000  92.25000
max    2.000000  94.00000  83.000000  93.00000


In [80]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
print("The Result table is:")
print(df)
print("\nvalues are:\n",df.aggregate(['max','min','count']))

The Result table is:
      Name  ut  Math  stat  DM
0    priya   1    90    80  90
1    priya   2    91    81  91
2   hridoy   1    92    82  92
3   hridoy   2    91    81  93
4   tanvir   1    94    83  91
5   tanvir   2    92    82  92
6  susmita   1    90    81  93
7  susmita   2    91    80  91

values are:
          Name  ut  Math  stat  DM
max    tanvir   2    94    83  93
min    hridoy   1    90    80  90
count       8   8     8     8   8


In [88]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
print("The Result table is:")
print(df)
print("\nvalues are:\n",df[['Math','DM']].aggregate(['max','min','count','sum'],axis=1))

The Result table is:
      Name  ut  Math  stat  DM
0    priya   1    90    80  90
1    priya   2    91    81  91
2   hridoy   1    92    82  92
3   hridoy   2    91    81  93
4   tanvir   1    94    83  91
5   tanvir   2    92    82  92
6  susmita   1    90    81  93
7  susmita   2    91    80  91

values are:
    max  min  count  sum
0   90   90      2  180
1   91   91      2  182
2   92   92      2  184
3   93   91      2  184
4   94   91      2  185
5   92   92      2  184
6   93   90      2  183
7   91   91      2  182


In [91]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
print("The Result table is:")
print(df)
print("\nvalues are:\n",df.sort_values(by=['Name','Math'],ascending=True))

The Result table is:
      Name  ut  Math  stat  DM
0    priya   1    90    80  90
1    priya   2    91    81  91
2   hridoy   1    92    82  92
3   hridoy   2    91    81  93
4   tanvir   1    94    83  91
5   tanvir   2    92    82  92
6  susmita   1    90    81  93
7  susmita   2    91    80  91

values are:
       Name  ut  Math  stat  DM
3   hridoy   2    91    81  93
2   hridoy   1    92    82  92
0    priya   1    90    80  90
1    priya   2    91    81  91
6  susmita   1    90    81  93
7  susmita   2    91    80  91
5   tanvir   2    92    82  92
4   tanvir   1    94    83  91


In [96]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
print("The Result table is:")
print(df)
g1=df.groupby('Name')
print(g1.first())

The Result table is:
      Name  ut  Math  stat  DM
0    priya   1    90    80  90
1    priya   2    91    81  91
2   hridoy   1    92    82  92
3   hridoy   2    91    81  93
4   tanvir   1    94    83  91
5   tanvir   2    92    82  92
6  susmita   1    90    81  93
7  susmita   2    91    80  91
         ut  Math  stat  DM
Name                       
hridoy    1    92    82  92
priya     1    90    80  90
susmita   1    90    81  93
tanvir    1    94    83  91


In [98]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
g1=df.groupby('Name')
print(g1.get_group('susmita'))

      Name  ut  Math  stat  DM
6  susmita   1    90    81  93
7  susmita   2    91    80  91


In [99]:
g1.groups

{'hridoy': [2, 3], 'priya': [0, 1], 'susmita': [6, 7], 'tanvir': [4, 5]}

In [102]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
g1=df.groupby('Name')
print(g1.groups)

{'hridoy': [2, 3], 'priya': [0, 1], 'susmita': [6, 7], 'tanvir': [4, 5]}


In [103]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
g1=df.groupby('Name')
print(g1.size())

Name
hridoy     2
priya      2
susmita    2
tanvir     2
dtype: int64


In [105]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
g1=df.groupby(['Name','ut'])
print(g1.first())

            Math  stat  DM
Name    ut                
hridoy  1     92    82  92
        2     91    81  93
priya   1     90    80  90
        2     91    81  91
susmita 1     90    81  93
        2     91    80  91
tanvir  1     94    83  91
        2     92    82  92


In [110]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
g1=df.groupby(['ut'])
print(g1['Math'].aggregate(['mean','max','min','var','std']))

     mean  max  min       var       std
ut                                     
1   91.50   94   90  3.666667  1.914854
2   91.25   92   91  0.250000  0.500000


In [112]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
df2=df[df.ut==2]
print("\nThe Result of unit test 2:")
print(df2,"\n")
df2.reset_index(inplace=True)
print(df2)


The Result of unit test 2:
      Name  ut  Math  stat  DM
1    priya   2    91    81  91
3   hridoy   2    91    81  93
5   tanvir   2    92    82  92
7  susmita   2    91    80  91 

   index     Name  ut  Math  stat  DM
0      1    priya   2    91    81  91
1      3   hridoy   2    91    81  93
2      5   tanvir   2    92    82  92
3      7  susmita   2    91    80  91


In [126]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
df2=df[df.ut==2]
df2.set_index('Name',inplace=True)
print(df2)
df2.reset_index('Name',inplace=True)
print(df2)

         ut  Math  stat  DM
Name                       
priya     2    91    81  91
hridoy    2    91    81  93
tanvir    2    92    82  92
susmita   2    91    80  91
      Name  ut  Math  stat  DM
0    priya   2    91    81  91
1   hridoy   2    91    81  93
2   tanvir   2    92    82  92
3  susmita   2    91    80  91


In [133]:
import pandas as pd
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,92,91,94,92,90,91],
        'stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,92,93,91]}
df=pd.DataFrame(result)
df2=df[df.ut==2]
df2.reset_index(inplace=True)
print(df2)
print(df2.drop(columns=['index']))


   index     Name  ut  Math  stat  DM
0      1    priya   2    91    81  91
1      3   hridoy   2    91    81  93
2      5   tanvir   2    92    82  92
3      7  susmita   2    91    80  91
      Name  ut  Math  stat  DM
0    priya   2    91    81  91
1   hridoy   2    91    81  93
2   tanvir   2    92    82  92
3  susmita   2    91    80  91


In [10]:
import pandas as pd
data={'Store':['S1','S4','S3','S1','S2','S3','S1','S2','S3'],
      'Year':[2016,2016,2016,2017,2017,2017,2018,2018,2018],
      'Total_sales(Rs)':[12000,330000,420000,20000,10000,450000,30000, 11000,89000],
      'Total_profit(Rs)':[1100,5500,21000,32000,9000,45000,3000,1900,23000]
}
df=pd.DataFrame(data)
print(df,'\n')
pivot2=df.pivot(index='Store',columns='Year',values=['Total_sales(Rs)','Total_profit(Rs)'])
print(pivot2)

  Store  Year  Total_sales(Rs)  Total_profit(Rs)
0    S1  2016            12000              1100
1    S4  2016           330000              5500
2    S3  2016           420000             21000
3    S1  2017            20000             32000
4    S2  2017            10000              9000
5    S3  2017           450000             45000
6    S1  2018            30000              3000
7    S2  2018            11000              1900
8    S3  2018            89000             23000 

      Total_sales(Rs)                    Total_profit(Rs)                  
Year             2016      2017     2018             2016     2017     2018
Store                                                                      
S1            12000.0   20000.0  30000.0           1100.0  32000.0   3000.0
S2                NaN   10000.0  11000.0              NaN   9000.0   1900.0
S3           420000.0  450000.0  89000.0          21000.0  45000.0  23000.0
S4           330000.0       NaN      NaN           5

In [17]:
import pandas as pd
import numpy as np
data={'Item':['Pen','Pen','Pencil','Pencil','Pen','Pen'],
      'Color':['Red','Red','Black','Black','Blue','Blue'],
      'Price(Rs)':[10,25,7,5,50,20],
      'Units_in_stock':[50,10,47,34,55,14]
}
df=pd.DataFrame(data)
print(df)
pivot3=df.pivot_table(index='Item',columns='Color',values='Units_in_stock',aggfunc=[sum,max,np.mean,len])
print(pivot3)

     Item  Color  Price(Rs)  Units_in_stock
0     Pen    Red         10              50
1     Pen    Red         25              10
2  Pencil  Black          7              47
3  Pencil  Black          5              34
4     Pen   Blue         50              55
5     Pen   Blue         20              14
         sum               max              mean               len          
Color  Black  Blue   Red Black  Blue   Red Black  Blue   Red Black Blue  Red
Item                                                                        
Pen      NaN  69.0  60.0   NaN  55.0  50.0   NaN  34.5  30.0   NaN  2.0  2.0
Pencil  81.0   NaN   NaN  47.0   NaN   NaN  40.5   NaN   NaN   2.0  NaN  NaN


In [31]:
import pandas as pd
import numpy as np
result={'Name':['priya','priya','hridoy','hridoy','tanvir','tanvir','susmita','susmita'],
        'ut':[1,2,1,2,1,2,1,2],
        'Math':[90,91,np.NaN,91,94,92,90,91],
        'Stat':[80,81,82,81,83,82,81,80],
        'DM':[90,91,92,93,91,np.NaN,93,91]}
df=pd.DataFrame(result)
print("The Result table is:\n",df)
df1 = df.fillna(method='bfill')
print("New dataframe:\n",df1)

The Result table is:
       Name  ut  Math  Stat    DM
0    priya   1  90.0    80  90.0
1    priya   2  91.0    81  91.0
2   hridoy   1   NaN    82  92.0
3   hridoy   2  91.0    81  93.0
4   tanvir   1  94.0    83  91.0
5   tanvir   2  92.0    82   NaN
6  susmita   1  90.0    81  93.0
7  susmita   2  91.0    80  91.0
New dataframe:
       Name  ut  Math  Stat    DM
0    priya   1  90.0    80  90.0
1    priya   2  91.0    81  91.0
2   hridoy   1  91.0    82  92.0
3   hridoy   2  91.0    81  93.0
4   tanvir   1  94.0    83  91.0
5   tanvir   2  92.0    82  93.0
6  susmita   1  90.0    81  93.0
7  susmita   2  91.0    80  91.0
